language: node_js
node_js:
  - '8'
cache:
  yarn: true
cache:
  - node_modules
before_install:
  - npm i -g yarn
install:
  - lerna bootstrap
  - yarn add coveralls --ignore-workspace-root-check
script:
  - yarn run lint
  - yarn run coverage
after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
