language: node_js
node_js:
  - "6"
cache:
  - node_modules
install:
  - npm install
  - npm install codeclimate-test-reporter
script:
  - gulp lint
  - npm run coverage
after_success:
  - node_modules/.bin/codeclimate-test-reporter < coverage/lcov.info
